### ISSUE TITLE
Inaccurate Minimum marks required to clear a component

### ISSUE THREAD

**Issue by nightcoder26** [sanjay7178/vRevamp#10]
## Description
The minimum marks required to clear a component are miscalculated , considering all the marks of the course are not yet released it shouldn't conclude anything with red/green colour 

## Screenshot
![image](https://github.com/sanjay7178/vRevamp/assets/77844703/f35ca67b-1215-4d1e-abcf-ceb94a2792d4)

This is another course from win sem 
![image](https://github.com/sanjay7178/vRevamp/assets/77844703/4c5b45c9-5d03-4f54-83d7-6b62d4202a61)

## Possible solution
- A seperate colour can be used for subjects whose quizzes, assignments etc marks arent all updated.
- You can mention how many more marks are required to pass a particular component instead of showing maximum or minimum marks

**Comment by sanjay7178** [comment]
Resolved Temporarily
