### ISSUE TITLE
Course Page download issue

### ISSUE THREAD

**Issue by Sarath191181208** [sanjay7178/vRevamp#6]
**The original URL shouldn't change if you ask me we must extend the functionality rather than changing it .....**

When trying to download the selected file it's downloading the html file rather than the pdf version. 
<img width="253" alt="Screenshot 2023-02-09 at 10 12 41 AM" src="https://user-images.githubusercontent.com/74459981/217719774-4901abad-7886-4cf8-ac6c-9fbebe7dcff9.png">

**Comment by sanjay7178** [comment]
Fixed the issue with course page 
added the new query for hooking up registration number

![image](https://user-images.githubusercontent.com/97831658/218248927-01998f36-6add-49a8-9a87-4773eecfd1d8.png)

**Comment by sanjay7178** [comment]
Now it works i think i will make a commit
